[package]
name = "rust_crypto"
version = "1.2.0"
edition = "2024"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3", features = ["napi6"] }
napi-derive = "3"
rand = "0.8"

[build-dependencies]
napi-build = "2.2.3"
